### ISSUE TITLE
1.0.0?

### ISSUE THREAD

**Issue by dcousens** [Prestaul/jsend#4]
Any reason not to be at 1.0.0?

**Comment by Prestaul** [comment]
Probably not. Bad form on my part so thanks for the question. I was on vacation last week but I'll bump it later today.

**Comment by Prestaul** [comment]
@dcousens and @selfcontained, before I go to v1.0.0 I'm thinking of removing the the `callback` and `responder` methods which were never documented, I don't think I've ever seen used, and simple for anyone to duplicate if they need the functionality. If either of you have objections then now is the time to shout.

FWIW: `callback` let you wrap a node-style callback (i.e. `(err, data)`) with a function that you could call with a jsend payload instead.  `responder` would do the opposite. Wrap a function that expects a jsend payload so that you can call it with `(err, data)` instead.

**Comment by dcousens** [comment]
@Prestaul I agree, that interface has been mostly useless for me, as I manually verify this all my self.
I mostly use the `jsend.middleware` for the convenience functions `res.jsend.error` and co.

**Comment by selfcontained** [comment]
Sounds good to me.

**Comment by Prestaul** [comment]
Published v1.0.0 with updated docs and sans-unneeded-methods. @dcousens thanks for the little push.
